const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const files = [
  { name: 'main', filePath: path.join(__dirname, '..', 'electron', 'main.cjs') },
  { name: 'server', filePath: path.join(__dirname, '..', 'server', 'index.js') },
];

const hashes = {};
for (const { name, filePath } of files) {
  if (fs.existsSync(filePath)) {
    const code = fs.readFileSync(filePath, 'utf-8');
    hashes[name] = crypto.createHash('sha256').update(code).digest('hex');
    console.log(`  ${name}: ${hashes[name]}`);
  } else {
    console.warn(`  ${name}: NOT FOUND (${filePath})`);
    hashes[name] = null;
  }
}

const outPath = path.join(__dirname, '..', 'electron', 'integrity.cjs');
const code = `// Auto-generated by tools/compute-hashes.cjs — do not edit manually
module.exports = ${JSON.stringify(hashes, null, 2)};
`;
fs.writeFileSync(outPath, code, 'utf-8');
console.log(`Written ${outPath}`);
